50 funds receiver
knownorigin/known-origin-contracts-v3 pull request #52
Opened 2021-11-23 10:04 UTC by andygray

* [x] deploy receiver clone to mainnet
* [x] add handler 
* [x] set up clone

2021-11-23 11:01 UTC, jamesmorgan requested changes
Minor comments

2021-11-23 11:01 UTC, jamesmorgan commented on scripts/11_create_v1_funds_receiver_clone.js
> +  // 0xb4bb0960b5095e5a0abd07d18803f45c4c4eadf6 RINKEBY
Can we add to the `README` and verify any sources on both networks to be consistent with the others contracts

2021-11-23 11:01 UTC, jamesmorgan commented on scripts/11_create_v1_funds_receiver_clone.js
> +  // 0x9b4E02227952214e1cD4aE60ed757589f2DF9661 RINKEBY
Ditch comment if not useful

2021-11-23 11:01 UTC, jamesmorgan commented on scripts/10_setup_v1_funds_receiver_clone.js
> +  // 0x2e9B9Eea4611163C38F5831fCbdBD113424772f7 RINKEBY
Add to README is useful, ditch comment

2021-11-26 16:32 UTC, vince0656 reviewed
looks great

2021-11-26 16:32 UTC, vince0656 commented on scripts/11_create_v1_funds_receiver_clone.js
> +];
I would use `getAddress` from ethers to make sure these are all valid addresses

2021-11-26 16:32 UTC, vince0656 commented on scripts/11_create_v1_funds_receiver_clone.js
> +];
get address will either return the checksummed address or blow up so needs to be done in a try catch and in the catch need to stop the script running to show that an address is invalid

2021-11-26 16:32 UTC, vince0656 commented on scripts/11_create_v1_funds_receiver_clone.js
> +const twoPercent = '200000';
whats the decimal places? just checking decimal places are correct

2021-11-26 16:32 UTC, vince0656 commented on scripts/11_create_v1_funds_receiver_clone.js
> +const prompt = require('prompt-sync')();
I think you will find coming back to the file confusing based on the name. This file should be called something like 'setup_collab'

2021-11-26 16:36 UTC, andygray commented on scripts/11_create_v1_funds_receiver_clone.js
> +const twoPercent = '200000';
I checked on rinkeby...

2021-12-01 11:24 UTC, merged