Marketplace upgradable
knownorigin/known-origin-contracts-v3 pull request #55
Opened 2022-01-25 15:15 UTC by andygray

* [x] new `BaseUpgradableMarketplace`
* [x] updated `contracts/marketplace/KODAV3GatedMarketplace.sol`
* [x] new `contracts/marketplace/KODAV3GatedMarketplaceV2.sol`
* [x] test to show state stays the same and new function exists

2022-01-25 15:26 UTC, d-eng-ltd commented on contracts/marketplace/KODAV3GatedMarketplace.sol
>  import "hardhat/console.sol";
`console.sol`

2022-01-25 15:26 UTC, d-eng-ltd commented on contracts/marketplace/KODAV3GatedMarketplaceV2.sol
> +import "hardhat/console.sol";
`console.sol`

2022-01-25 15:29 UTC, d-eng-ltd commented on contracts/marketplace/KODAV3GatedMarketplaceV2.sol
> +        Sale memory sale = sales[saleId];
`storage` cheaper to use for structs but be careful nothing modifies the struct. Equally, if something is supposed to modify the struct then you'll need storage anyway

2022-01-25 15:30 UTC, d-eng-ltd commented on contracts/marketplace/KODAV3GatedMarketplaceV2.sol
> +    }
lol

2022-01-27 09:21 UTC, jamesmorgan commented on abis/ClaimableFundsReceiverV1.json
> -    "inputs": [
I'm wondering why the ABIs have changed?

2022-01-27 09:46 UTC, jamesmorgan requested changes

2022-01-27 09:46 UTC, jamesmorgan commented on abis/ClaimableFundsSplitterV1.json
> -    "inputs": [
I'm wondering why the ABIs have changed?

2022-01-27 09:46 UTC, jamesmorgan commented on contracts/marketplace/BaseUpgradableMarketplace.sol
> +    function _isListingPermitted(uint256 _id) internal virtual returns (bool);
Maybe we ditch this if its not used in the impl?

2022-01-27 09:46 UTC, jamesmorgan commented on contracts/marketplace/KODAV3GatedMarketplaceV2.sol
> +    mapping(uint256 => uint256) private saleCommission;
does this need to be public?

2022-01-27 09:46 UTC, jamesmorgan commented on contracts/marketplace/KODAV3GatedMarketplaceV2.sol
> +            accessControls.hasAdminRole(_msgSender()) || koda.getCreatorOfEdition(_editionId) == _msgSender(),
I would flip this round `koda.getCreatorOfEdition(_editionId) == _msgSender() || accessControls.hasAdminRole(_msgSender())` as we want to save GAS for users and a quick exit on them using it is preferable IMO

2022-01-27 09:46 UTC, jamesmorgan commented on contracts/marketplace/KODAV3GatedMarketplaceV2.sol
> +        editionToSale[_editionId] = saleId;
Wondering if an edition can in theory be in two phases at once? i.e. should we check and enforce sale per edition at a time?

2022-01-27 09:46 UTC, jamesmorgan commented on contracts/marketplace/KODAV3GatedMarketplaceV2.sol
> +        emit MintFromSale(_saleId, sale.editionId, _phaseId, _msgSender(), _mintCount);
I think it would be useful to model out in the basic state flow diagram the process of mint, listing and buying through these marketplace functions - they can added to these docs https://github.com/knownorigin/documentation/tree/master/architecture/v3/marketplace

2022-01-27 09:46 UTC, jamesmorgan commented on contracts/marketplace/KODAV3GatedMarketplaceV2.sol
> +        require(koda.editionExists(_editionId), 'edition does not exist');
Is this needed if we check sale ID below?

2022-01-27 09:46 UTC, jamesmorgan commented on contracts/marketplace/KODAV3GatedMarketplaceV2.sol
> +        require(koda.editionExists(_editionId), 'edition does not exist');
Is this needed since we check below?

2022-01-27 09:46 UTC, jamesmorgan commented on contracts/marketplace/KODAV3GatedMarketplaceV2.sol
> +    function canMint(uint256 _saleId, uint _phaseId, uint256 _index, address _account, bytes32[] calldata _merkleProof) public view returns (bool) {
Should we also expose a method to check if a user can mint which takes into account mint limits?

2022-01-27 09:46 UTC, jamesmorgan commented on contracts/marketplace/KODAV3GatedMarketplaceV2.sol
> +    ) internal override returns (uint256) {
do we need this if not used?

2022-01-27 09:46 UTC, jamesmorgan commented on contracts/marketplace/KODAV3GatedMarketplaceV2.sol
> +    }
Ditch if needed?

2022-01-27 09:46 UTC, jamesmorgan commented on test/marketplace/KODAV3GatedMarketplace.upgrabable.test.js
> +});
Can we add a test to prove the upgrade path? Even if its a new instance of the existing marketplace?

2022-02-14 18:15 UTC, merged